package:
  name: memo.apartment-block-model-only
  version: "0.1.2"

about:
  summary: "For testing: an empty model file (standard/dark night)"

requirements:
  run:
    # pins the dummy package to version 1.* or 2.* (dark night/standard night),
    # so that dark night and standard night variants of this package are built
    - memo.dark-night-dummy {{ darknight }}.*

build:
  number: 2
  noarch: generic
  script_env:
    - SC4PAC_FILESLIST={{ 'files-dn.txt' if darknight == '1' else 'files.txt' }}
    - SC4PAC_SUBFOLDER=200-residential/270-high-density
  script: bash "$RECIPE_DIR/move-files.sh"
