package:
  name: memo.apartment-block-relot
  version: "0.1.4"

about:
  summary: "For testing: a relotted version depending on the original model and props"

requirements:
  run:
    - memo.apartment-block-model-only
    - memo.mega-props-vol-42

build:
  number: 4
  noarch: generic
  script_env:
    - SC4PAC_FILESLIST=files.txt
    - SC4PAC_SUBFOLDER=200-residential/270-high-density
  script: bash "$RECIPE_DIR/move-files.sh"
